name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_followup: yes
          plugin_followup_sections: repositories
          repositories: 1000
          repositories_forks: yes
  
  github-metrics-extended:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ALL_METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          config_order: languages, habits, reactions
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_threshold: 0%
          plugin_languages_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_from: 200
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_details: count, percentage
          repositories_forks: yes
          filename: github-metrics-languages.svg
