name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_followup: yes
          plugin_followup_sections: repositories
          repositories: 1000
          repositories_forks: yes
  
  github-metrics-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ALL_METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_threshold: 0%
          plugin_languages_categories: markup, programming
          plugin_languages_recent_days: 365
          repositories_forks: yes
          filename: github-metrics-languages.svg
  
  github-metrics-habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ALL_METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          repositories_forks: yes
          filename: github-metrics-habits.svg
  
  github-metrics-reactions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ALL_METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_details: percentage
          repositories_forks: yes
          filename: github-metrics-reactions.svg
