name: Metrics
on:
  schedule: 
    - {cron: "0 3 * * *"}  # 00:00 BRT (UTC-3)
    - {cron: "0 15 * * *"} # 12:00 BRT (UTC-3)
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_followup: yes
          plugin_followup_sections: repositories
          repositories: 1000
          repositories_forks: yes
  
  github-metrics-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ALL_METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_threshold: 0%
          plugin_languages_categories: markup, programming
          plugin_languages_recent_days: 365
          repositories_forks: yes
          filename: github-metrics-languages.svg
  
  github-metrics-habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: calilkhalil/metrics@fix-habits-author-undefined
        with:
          token: ${{ secrets.ALL_METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          users_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_days: 30
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 8
          plugin_habits_trim: yes
          repositories_forks: yes
          filename: github-metrics-habits.svg
  
  github-metrics-notable:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ALL_METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_notable_from: all
          plugin_notable_types: commit
          plugin_notable_filter: stars:>285
          filename: github-metrics-notable.svg
  
  github-metrics-fortune:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ALL_METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          plugin_fortune: yes
          repositories_forks: yes
          filename: github-metrics-fortune.svg
  
  github-metrics-reactions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ALL_METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_details: percentage
          repositories_forks: yes
          filename: github-metrics-reactions.svg
