name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_followup: yes
          plugin_followup_sections: repositories
          repositories: 1000
          repositories_forks: yes
  
  github-metrics-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ALL_METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 120

          plugin_languages_categories: markup, programming, data
          
          plugin_languages_colors: github
          
          plugin_languages_details: percentage
          
          plugin_languages_limit: 12
          
          plugin_languages_threshold: 0%
          
          plugin_languages_recent_load: 10000
          plugin_languages_recent_days: 1000
          
          plugin_languages_sections: most-used

          plugin_languages_indepth: no
          
          repositories_forks: yes
          
          filename: github-metrics-languages.svg
