name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_followup: yes
          plugin_followup_sections: repositories
          repositories: 1000
          repositories_forks: yes
  
  github-metrics-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ALL_METRICS_TOKEN }}
          user: calilkhalil
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          config_padding: 0, 8 + 11%
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60

          plugin_languages_categories: markup, programming
          
          plugin_languages_colors: github
          
          plugin_languages_details: percentage, bytes-size
          
          plugin_languages_limit: 15
          
          plugin_languages_threshold: 0.5%
          
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          
          plugin_languages_sections: most-used
          
          plugin_languages_indepth: no
          
          plugin_languages_skipped: lowlighter
          
          config_display: large
          
          filename: github-metrics-languages.svg
